# Generated by Django 2.1 on 2021-04-23 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='MyData',
        ),
    ]
